### ISSUE TITLE
AF_XDP: Out of VI instances with given attributes (-16)

### ISSUE THREAD

**Issue by ol-damirm** [Xilinx-CNS/onload#115]
I see the following error message, when trying to run application under Onload in AF_XDP mode:
```shell
onload nc -l 12345
oo:nc.openbsd[64020]: netif_tcp_helper_alloc_u: ERROR: Failed to allocate stack (rc=-16)
See kernel messages in dmesg or /var/log/syslog for more details of this failure

# Here are entries from /var/log/syslog
[41316.063462] [sfc efrm] efrm_vi_alloc: Out of VI instances with given attributes (-16)
[41316.074187] [sfc efrm] efrm_vi_alloc: Out of VI instances with given attributes (-16)
```
I haven't seen this before. Git bisect says it's a regression from a commit cf9a523901fa "ON-14118: Move accept_vi_constraints to efhw hal".

**Comment by ol-alexandra** [comment]
The issue have been finally fixed, see https://github.com/Xilinx-CNS/onload/pull/119#issuecomment-1336503388

I do not see any button to close the issue on github.  Probably it is the thing to be done by AMD developers.
