### ISSUE TITLE
The DKMS package built by onload_mkdkms should depend on libcap-devel

### ISSUE THREAD

**Issue by ddrinka** [Xilinx-CNS/onload#12]
We use DKMS for delivery of Onload to our production machines.  `onload_mkdkms` works fine, but produces an RPM that can't build on a default install.

`libcap-devel` should be added as a dependency for the DKMS RPM, to avoid the error:
```
sys/capability.h: No such file or directory
```

**Comment by abower-xilinx** [comment]
Thanks for identifying this. I assume the underlying issue is actually with the building of the userspace RPM. This is fixed in ef43908bd2779a88bf71b3db6ff3a91608fb857a. Please do create a pull request if you find this is insufficient!
