### ISSUE TITLE
Recommend changing shebang in scripts/run_unit_tests.sh to use Bash shell

### ISSUE THREAD

**Issue by cpaolini** [Xilinx-CNS/onload#14]
Default shebang is Bourne shell in run_unit_tests.sh.  Under  Ubuntu 18.04.5 LTS:
root@aptd:~/onload# ./scripts/run_unit_tests.sh
./scripts/run_unit_tests.sh: 12: ./scripts/run_unit_tests.sh: Syntax error: "(" unexpected

Changing to "#! /bin/bash -e" allows script to execute:

root@aptd:~/onload# ./scripts/run_unit_tests.sh
Building tests
make: Entering directory '/home/paolini/onload/build/gnu_x86_64'
make[1]: Entering directory '/home/paolini/onload/build/gnu_x86_64/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/include'
make[1]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/citools'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/citools'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/ciapp'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/ciapp'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/onload_ext'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/onload_ext'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/ciul'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/ciul'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/kcompat'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/kcompat'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/cplane'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/cplane'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/transport'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/transport/ip'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/transport/ip'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/transport/common'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/transport/common'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/lib/transport/unix'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/transport/unix'
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib/transport'
make[1]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/lib'
make[1]: Entering directory '/home/paolini/onload/build/gnu_x86_64/driver'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers'
make[4]: Entering directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers/net'
make[5]: Entering directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers/net/ethernet'
make[6]: Entering directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers/net/ethernet/sfc'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers/net/ethernet/sfc'
make[5]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers/net/ethernet'
make[4]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers/net'
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net/drivers'
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/driver/linux_net'
make[1]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/driver'
make[1]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tools'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tools/cplane'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tools/cplane'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tools/onload_helper'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tools/onload_helper'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tools/ip'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tools/ip'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tools/solar_clusterd'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tools/solar_clusterd'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tools/onload_remote_monitor'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tools/onload_remote_monitor'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tools/onload_mibdump'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tools/onload_mibdump'
make[1]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tools'
make[1]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/ef_vi'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/ef_vi'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/wire_order'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/wire_order'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/tproxy_preload'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/tproxy_preload'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/hwtimestamping'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/hwtimestamping'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/sync_preload'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/sync_preload'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/oof'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/oof'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/onload_remote_monitor'
make[4]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/onload_remote_monitor/internal_tests'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/onload_remote_monitor/internal_tests'
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/onload_remote_monitor'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/cplane_unit'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/cplane_unit'
make[3]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/cplane_sysunit'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/cplane_sysunit'
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/orm_test_client'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/orm_test_client'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/rtt'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/rtt'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/syscalls'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/syscalls'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/tap'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/tap'
make[2]: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/trade_sim'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/trade_sim'
make[1]: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests'
make: Leaving directory '/home/paolini/onload/build/gnu_x86_64'
Running tests
make: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/oof'
/usr/bin/timeout 240 prove --exec ' ' \
 "./oof_test sanity" "./oof_test multicast_sanity" "./oof_test namespace_sanity" "./oof_test namespace_macvlan_move"
./oof_test sanity .................. ok
./oof_test multicast_sanity ........ ok
./oof_test namespace_sanity ........ ok
./oof_test namespace_macvlan_move .. ok
All tests successful.
Files=4, Tests=158,  0 wallclock secs ( 0.04 usr +  0.02 sys =  0.06 CPU)
Result: PASS
make: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/oof'
make: Entering directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/cplane_unit'
/usr/bin/timeout 600 prove -j2 --merge --exec '' \
 ./test_route ./test_route_expire ./test_arp_expire ./test_route_stress ./test_teambond ./test_namespace ./test_service_dnat
./test_route ......... ok
./test_route_expire .. ok
./test_arp_expire .... ok
./test_route_stress .. ok
./test_namespace ..... ok
./test_service_dnat .. ok
./test_teambond ...... ok
All tests successful.
Files=7, Tests=167, 50 wallclock secs (16.74 usr  0.70 sys + 76.20 cusr  0.47 csys = 94.11 CPU)
Result: PASS
make: Leaving directory '/home/paolini/onload/build/gnu_x86_64/tests/onload/cplane_unit'
All tests PASSED

**Comment by abower-xilinx** [comment]
Hi, thanks - this is fixed in 9612443b4120231baeefa3c913f45ef19ab83fc0.
