### ISSUE TITLE
dkms.conf does not include sfc_driverlink

### ISSUE THREAD

**Issue by ajschorr** [Xilinx-CNS/onload#145]
onload_install installs sfc_driverlink.ko, but this kernel module is not mentioned
in dkms.conf. Shouldn't it be in there?

**Comment by nodakai** [comment]
As a quick workaround, I manually edited `/usr/src/openonload-(my version)/dkms.conf` to add the following section

```
BUILT_MODULE_NAME[4]="sfc_driverlink"
BUILT_MODULE_LOCATION[4]="../build/build/${arch}_linux-${kernelver}/driver/linux_driverlink"
DEST_MODULE_LOCATION[4]="/extra"
```

after this section for `onload`: https://github.com/Xilinx-CNS/onload/blob/649bdc88b31c8d809b0e2ae46dc20a4570b798b1/scripts/onload_misc/dkms.conf#L43

and then ran `dkms unbuild openonload/(myversion)` followed by `dkms install openonload/(my version)`

Now I have

```
$ ls extra
driverlink_api.h  onload.symvers  sfc_char.ko        sfc_resource.ko
filter.h          sfc.ko          sfc_char.symvers   sfc_resource.symvers
onload.ko         sfc.symvers     sfc_driverlink.ko
$ pwd
/usr/lib/modules/5.10.0-20-amd64
```

Interestingly the template file for Debian packaging already included `sfc_driverlink` (but with a different convention for `BUILT_MODULE_LOCATION`)
https://github.com/Xilinx-CNS/onload/blob/649bdc88b31c8d809b0e2ae46dc20a4570b798b1/scripts/debian/debian-templ/type-dkms.dkms#L27

**Comment by ajschorr** [comment]
Agreed. I did the same.

**Comment by jfeather-amd** [comment]
Thanks for raising this issue @ajschorr, and for providing valuable discussion @nodakai. Annoyingly, pushing a fix to my fork for review seems to have closed the issue, but the fix has still not been merged! It should filter through to this repo soon, but I'll reopen this until then!
