### ISSUE TITLE
dkms.conf specifies REMAKE_INITRD="yes", but this feature is now deprecated

### ISSUE THREAD

**Issue by ajschorr** [Xilinx-CNS/onload#146]
In dkms.conf, it says:

REMAKE_INITRD="yes"

But dkms has deprecated REMAKE_INITRD. One gets this error:

bash-5.1$ dkms status onload
Deprecated feature: REMAKE_INITRD
onload/8.0.2.51, 5.14.0-115.el9.x86_64, x86_64: installedDeprecated feature: REMAKE_INITRD
 (original_module exists)

**Comment by jfeather-amd** [comment]
Thanks for raising this issue @ajschorr! As I mentioned in #145, I have a patch in review for this issue too but GitHub chose to close these early, so I'll be reopening this for now!
