### ISSUE TITLE
[X3522 low NIC]onload_tcpdump is notworking but tcpdump is still ok

### ISSUE THREAD

**Issue by nguyentdnb95** [Xilinx-CNS/onload#172]
Dear teams, 
I have X3522 low latency nic. I have set up transferring data from another server to X3522 port and tried to capture it in `onload_tcpdump` but it is not working. But `tcpdump` command could capture that data, so that onload_tcpdump does not work. Please help to check where the issue is. 
The environment setup on ubuntu 20.04, with kernel version 5.15.0-83-generic
Enviroment setup 

![image](https://github.com/Xilinx-CNS/onload/assets/30515674/ac99e0fd-c433-44a5-aff7-56d7c01e7f86)
![image](https://github.com/Xilinx-CNS/onload/assets/30515674/0e0a853a-64d1-4c5d-b1f1-24aa7dcb3d36)

Tested by `tcpdump`
![image](https://github.com/Xilinx-CNS/onload/assets/30515674/6c56e2d0-b76e-42fc-9367-6b90618944eb)

Tested by `onload_tcpdump`
![image](https://github.com/Xilinx-CNS/onload/assets/30515674/2a546a6a-3df0-45f0-819c-180b8456e50f)

**Comment by abower-amd** [comment]
Hi @nguyentdnb95, as this is a supported OpenOnload on a supported NIC the team at support-nic@amd.com would be best placed to advise!
