### ISSUE TITLE
Syscall epoll_pwait2 is not accelerated

### ISSUE THREAD

**Issue by vsolontsov-ll** [Xilinx-CNS/onload#174]
Hello!

Since Linux kernel v5.11 there's a new  `epoll_pwait2()` [syscall](https://man7.org/linux/man-pages/man2/epoll_wait.2.html). The only difference is that it takes timeout as `struct timespect`. 
Would be great to accelerate this syscall and use it internally if available.

**Comment by ligallag-amd** [comment]
Thanks for raising this issue. This has been resolved as of 1897df7821d8347d8b2e3b82e88197dc70b5b4ae
