### ISSUE TITLE
timestamps with af_xdp

### ISSUE THREAD

**Issue by wrfeewrtgaqwfrwaq** [Xilinx-CNS/onload#214]
Sorry to bother, but I can't find it anywhere in the documentation. Does onload use hardware timestamps when in af_xdp mode?

**Comment by ivatet-amd** [comment]
The recently merged https://github.com/Xilinx-CNS/onload/pull/167 introduces HW timestamps for AF_XDP. However, the underlying network driver must implement the `xmo_rx_timestamp()` function, which implies the use of newer Linux kernels. Hope that gives you some useful pointers.

AF_XDP is not commercially supported in Onload, so there is only limited coverage in the documentation.

**Comment by wrfeewrtgaqwfrwaq** [comment]
Do you maybe know what exactly is minimum required kernel version?

**Comment by wrfeewrtgaqwfrwaq** [comment]
Thanks a lot!
