### ISSUE TITLE
Kernel 5.11 support in conjunction with TCPDirect

### ISSUE THREAD

**Issue by cjelsa** [Xilinx-CNS/onload#23]
We would need the 5.11 support, but with TCPDirect. Would it be possible to create a patch for the released version for us to be able to compile it on newer kernels?

**Comment by abower-xilinx** [comment]
Hi, thanks for visiting! Please e-mail support-nic@xilinx.com about support for TCPDirect.

**Comment by cjelsa** [comment]
Thank you
