### ISSUE TITLE
Linux kernel 5.10 OpenOnload release?

### ISSUE THREAD

**Issue by ido** [Xilinx-CNS/onload#35]
Could you issue a new supported/official OpenOnload release for Linux kernel version 5.10.x?  It's the latest longterm kernel and a few distributions are now using it.

**Comment by abower-xilinx** [comment]
> Could you issue a new supported/official OpenOnload release for Linux kernel version 5.10.x? It's the latest longterm kernel and a few distributions are now using it.

Hi @ido,

Your wish is our command!

Please find the new OpenOnload-7.1.2.141 release at https://support-nic.xilinx.com/ including support up to kernel version 5.12.
