### ISSUE TITLE
difference between   Xilinx-CNS/onload  and   majek/openonload

### ISSUE THREAD

**Issue by somewheve** [Xilinx-CNS/onload#40]
I notice that there are two repositories. and  `Xilinx-CNS/onload `  remove  `<zf/zf.h>` which is used by tcp_direct.   and   `<zf/zf.h>` can be found at  ` majek/openonload.`  

I am confused about this. 

and  https://support-nic.xilinx.com/wp/onload?sd=SF-116303-CD-9&pe=361  chapter6.1 told me to use `<zf/zf.h>`

**Comment by somewheve** [comment]
I want to know how to use  tcp_direct in the repository.

**Comment by abower-xilinx** [comment]
Hi @somewheve,

TCPDirect is not part of this repository - you need to obtain an OpenOnload release package from https://support-nic.xilinx.com/ to use TCPDirect.

The second repository you mention is not maintained by Xilinx.

If you need any help using the released versions of Onload please contact support-nic@xilinx.com

**Comment by somewheve** [comment]
got it , thank you

abower-xilinx ***@***.***> 于2021年8月25日周三 下午9:08写道：

**Comment by C8LUKA** [comment]
> Hi @somewheve,
> 
> TCPDirect is not part of this repository - you need to obtain an OpenOnload release package from https://support-nic.xilinx.com/ to use TCPDirect.
> 
> The second repository you mention is not maintained by Xilinx.
> 
> If you need any help using the released versions of Onload please contact [support-nic@xilinx.com](mailto:support-nic@xilinx.com)

sorry to disturb you，It is very kindly to show that anyway or any example to use tcp like tcp_direct with ef_vi or something

**Comment by somewheve** [comment]
I would like to ask if using tcp_direct  by rust  is possible ?

**Comment by C8LUKA** [comment]
> 

it seem that this repo would not add tcp_direct @_@
