### ISSUE TITLE
No kernel build at '/lib/modules/5.10.0-0.bpo.3-rt-amd64/build'

### ISSUE THREAD

**Issue by progettista6** [Xilinx-CNS/onload#45]
Hello everyone, 
I use a DELL Latitude 5520 computer (Intel i5), with operating system Ubuntu 18.04.5 LTS, Linux kernel 5.10.0-0.bpo.3-rt-amd64 and architecture x86-64. I tried to install OpenOnLoad, following the instructions in the paragraph "Building directly from repository" (https://github.com/Xilinx-CNS/onload/blob/master/DEVELOPING.md). 
In particular there seems to be some problems related to the drivers: as you can see from the figure, the kernel build is not found.

![onload issue](https://user-images.githubusercontent.com/89065330/135094864-0bae239e-ba8a-4ebd-9cea-72cc6e39d146.png)

Instead, running the same instructions on a generic kernel, the whole installation process went smoothly.

Has anyone had the same problem as me? Can you help me?

Thank you,
Best regards,
Emma

**Comment by ol-alexandra** [comment]
If you install `linux-image-5.10.0-0.bpo.3-rt-amd64` and want to build any module, you should also install `linux-headers-5.10.0-0.bpo.3-rt-amd64`.  It is organised this way for any Debian/Ubuntu kernel.

**Comment by abower-amd** [comment]
This should be resolved with the advice above, thanks! Closing.
