### ISSUE TITLE
VNICs and Stack isolation in Kubernetes

### ISSUE THREAD

**Issue by techthumb** [Xilinx-CNS/onload#49]
👋🏽 

## Our Setup
Tech stack:
- Solarflare Card
- Kubernetes
- Multus
- VNIC/MACVLAN

We are using the multus CNI plugin to:
- create a VNIC backed by the Solarflare card, and,
- attaching the VNIC as a secondary network interface to each pod

## Our Concern
Pods are able to view traffic associated with other pods via `onload_tcpdump`.

Additionally, `onload_stackdump` shows `Onload Stacks` associated with card regardless of which pod the stack was created in.

## Question
Is there a way to achieve isolation at the device level, such that pods are restricted to viewing traffic and stacks associated with the VNIC they have access to?

Thanks in advance

**Comment by iand-xilinx** [comment]
Thanks for opening this issue.  `onload_stackdump` and `onload_tcpdump` will map stacks in the current user namespace subject to the value of `EF_SHARE_WITH` for those stacks.  For commercial versions of Onload with Xilinx/Solarflare hardware you can open a support ticket by e-mailing support-nic@xilinx.com for detailed help with your particular use-case.
