### ISSUE TITLE
Run onload with TCP disabled

### ISSUE THREAD

**Issue by davidjl98** [Xilinx-CNS/onload#56]
Is there a way to run an application but disable onload from taking over TCP connections? I still want to use onload to accelerate UDP. I didn't see in the documentation a way to build/disable certain aspects of onload.

**Comment by sianj-xilinx** [comment]
You can configure this at runtime by setting the environment variable `EF_TCP=0`.

**Comment by sianj-xilinx** [comment]
(You can see the available environment variables for tuning behaviour with `onload_stackdump doc`.)

**Comment by davidjl98** [comment]
Thanks! Exactly what I needed
