### ISSUE TITLE
Conan package for user libraries

### ISSUE THREAD

**Issue by crucio55** [Xilinx-CNS/onload#58]
Would you consider adding packages to the [Conan repository](https://github.com/conan-io/conan-center-index) for building the user libraries?
The building process in not particularly complicated, so not much work will be required.

This would greatly simplify our work - and might help many others, too, with easy standardizing of their build system :relaxed:

**Comment by ol-alexandra** [comment]
In my humble opinion, building UL and kernel parts separately is a road to hell.

**Comment by crucio55** [comment]
Actually, we've been doing that for years, and it's been fine so far (:

It's probably a common use-case - building the executables remotely, and not on the server, that is.

**Comment by ol-alexandra** [comment]
We are talking about this github repository, right?  And how do you guarantee that modules and UL come from the same revision?

**Comment by crucio55** [comment]
Yeah, of course!
They might be compiled on different GCC versions though

**Comment by ol-alexandra** [comment]
Gcc version shouldn't be an issue.  In this case you are free to propose a patch.  I'm almost sure that nobody from Xilinx Onload team is familiar with the Conan.

**Comment by crucio55** [comment]
The thing is that the Conan recipe is pushed to their repository that I linked - and I don't think I can propose a patch there on behalf of Xilinx Onload... :sweat: 

Even if I do end up doing it, I'll probably have questions along the way. For example, get links for the source tarballs - there are no Github releases to take their links, and on the [official page](https://support-nic.xilinx.com/wp/onload) I couldn't find links that would work with `wget` and the like

Anyway, even if I build the initial Conan support, I won't exactly stay to maintain it, so that's something to consider for the Onload Xilinx team.

**Comment by abower-xilinx** [comment]
Thanks for the suggestion @crucio55! It's not realistic for us to maintain such a contribution either so I'm going to close this issue.

However, we would be happy to consider pull requests on this repository that helped anyone else working on packaging or integration of Onload.
