### ISSUE TITLE
Cannot terminate the child process through signal

### ISSUE THREAD

**Issue by jameslee5656** [Xilinx-CNS/onload#76]
Hi,

An issue about onload occurs during our deployment of the new machine with card SFN8542-PLUS x1 and onload-7.1.2.141.
We send a signal to terminate, onload process doesn't seem to send a terminate signal to its child process.

```
zero+ 23015  0.0  0.0  12536  3032 pts/4    Ss+  18:59   0:00  LD_LIBRARY_PATH=/with/tetrion/root/lib with -t /local/zerorisk_tw/demondrake/demondrake.mainline.ibp onload optiontrader    (This is a onload process)
zero+ 23016  2.8  3.6 3054224 2405844 pts/4 Rl+  18:59   0:09 optiontrader  (This is it's child process)
```

So when we kill the process 23015, 23015 seems only to terminate itself.
We then downgrade to onload-7.1.0.256 and it works fine for us.

How should we approach this for installing the newer version?

**Comment by rhughes-xilinx** [comment]
Hi James,

We use this bug tracker for issues with the code in the repository here, not for official releases. You can either:
- Upgrade your systems to the tip of master, test again, and discuss any issues you see here, or
- Use the links at https://www.xilinx.com/support/nic-support.html#cases for help with official Onload releases.

I will mention that we did a substantial rewrite of signal handling in 7.1.2 (necessary to support newer kernels), so I can easily believe that bugs might have crept in.
