### ISSUE TITLE
AF_XDP on Solarflare NIC

### ISSUE THREAD

**Issue by boyracer2020** [Xilinx-CNS/onload#84]
When using Onload on Solarflare NICs, is there a way to switch from kernel bypass onload to AF_XPD version of onload ?

When we register the solareflare dev (echo dev > ...) , we are still seeing kernel bypass in action and not AF_XDP. 

thanks, M.

**Comment by shirshen12** [comment]
@boyracer2020 see this reply link, it contains the solution and will solve your problem

https://github.com/Xilinx-CNS/onload/issues/55#issuecomment-984298407

**Comment by abower-amd** [comment]
Closed as already supported.
